---
dependencies:
  - role: kubernetes-apps/ansible
    tags:
      - apps

  - role: kubernetes-apps/efk
    when: efk_enabled
    tags:
      - apps
      - efk

  - role: kubernetes-apps/helm
    when: helm_enabled
    tags:
      - apps
      - helm

  - role: kubernetes-apps/registry
    when: registry_enabled
    tags:
      - apps
      - registry

  - role: kubernetes-apps/local_volume_provisioner
    when: local_volume_provisioner_enabled
    tags:
      - apps
      - local_volume_provisioner
      - storage

  - role: kubernetes-apps/cephfs_provisioner
    when: cephfs_provisioner_enabled
    tags:
      - apps
      - cephfs_provisioner
      - storage

  # istio role should be last because it takes a long time to initialize and
  # will cause timeouts trying to start other addons.
  - role: kubernetes-apps/istio
    when: istio_enabled
    tags:
      - apps
      - istio